# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: new-docker-app-rolebinding
  namespace: nv1
subjects:
- kind: ServiceAccount
  name: new-docker-app-serviceaccount
  namespace: nv1
roleRef:
  kind: Role
  name: new-docker-app-role
  apiGroup: rbac.authorization.k8s.io