apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo-app-deployment
  namespace: eswar
  labels:
    app: dotnetdemo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: dotnetdemo-app
    spec:
      initContainers:
      - name: init-setup
        image: busybox:latest
        command: ['sh', '-c', 'ls; pwd; sleep 10']
        envFrom:
        - configMapRef:
            name: dotnetdemo-app-deployment
      containers:
      - name: dotnetdemo-app
        image: eshwar0495/dotnet:latest  # Updated to use your Docker Hub repository
        ports:
        - containerPort: 9000
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 9000
          initialDelaySeconds: 8
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: dotnetdemo-app-deployment
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: dotnetdemo-app-deployment
