apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerjuly-deployement 
  namespace: esh
  labels:
    app: dockerjuly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerjuly
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: dockerjuly
    spec:
      initContainers:
      - name: init-setup
        image: busybox:latest
        command: ['sh', '-c', 'ls; pwd; sleep 10']
        envFrom:
        - configMapRef:
            name: dockerjuly-deployment
      containers:
      - name: dockerjuly
        image: dotnetdemo-app:latest
        ports:
        - containerPort: 9000
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 9000   # Corrected port to match the containerPort
          initialDelaySeconds: 8
          periodSeconds: 10
          failureThreshold: 3  # Corrected field name
          successThreshold: 1  # Corrected field name
        readinessProbe:
          httpGet:
            path: /readiness
            port: 9000  # Corrected port to match the containerPort
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: dockerjuly-deployment
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: dockerjuly-deployment